name: Docker Image CI

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
      
jobs:

  build:

    runs-on: ubuntu-latest
    env:
      MongoDB__Host: mongo
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      PORT: 4444:80

    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose -f SciencePaperAnalyzer/docker-compose.yml -f SciencePaperAnalyzer/docker-compose.ci.yml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs
      run: docker logs backend
    - name: Run test suite
      run: docker exec backend pytest --skip-auth
